spring.application.name=micro-users

spring.datasource.url=jdbc:mysql://localhost:3306/Users
spring.datasource.username=root
spring.datasource.password=


spring.jpa.hibernate.ddl-auto=create
spring.jpa.defer-datasource-initialization=true

spring.sql.init.mode=always

